# @package _global_
config:
  VERBOSE: True
  LOG_FREQUENCY: 100
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: True
      PERF_STAT_FREQUENCY: 10
      ROLLING_BTIME_FREQ: 313
    TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [torchvision_dataset]
      DATA_PATHS: []
      DATASET_NAMES: [CIFAR10]
      BATCHSIZE_PER_REPLICA: 256
      LABEL_TYPE: sample_index    # just an implementation detail. Label isn't used
      TRANSFORMS:
        - name: ImgReplicatePil
          num_times: 2
        - name: RandomResizedCrop
          size: 32
        - name: RandomHorizontalFlip
          p: 0.5
        - name: ImgPilColorDistortion
          strength: 0.5
        - name: ImgPilGaussianBlur
          p: 0.0
          radius_min: 0.1
          radius_max: 2.0
        - name: ToTensor
        - name: Normalize
          mean: [0.4914, 0.4822, 0.4465]
          std: [0.2023, 0.1994, 0.2010]
      COLLATE_FUNCTION: simclr_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/cifar10/
      DROP_LAST: True
  METERS:
    name: ""
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        BLOCK: BasicBlock
        FIRST_CONV_ORIG: False
        FIRST_MAXPOOL_ORIG: False
        DEPTH: 18
        WIDTH_MULTIPLIER: 1
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [512, 128], "use_relu": True, "use_bn": True, "skip_last_layer_relu_bn": False}],
        ["mlp", {"dims": [128, 128], "use_relu": True, "use_bn": True, "skip_last_layer_relu_bn": False}],
        ["mlp", {"dims": [128, 128], "skip_last_layer_relu_bn": True}],
        ["pawpro_head", {"dims": [128, 64]}],
      ]
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: apex
      GROUP_SIZE: 2
    AMP_PARAMS:
      USE_AMP: False
      AMP_ARGS: {"opt_level": "O3", "keep_batchnorm_fp32": True, "master_weights": True, "loss_scale": "dynamic"}
  LOSS:
      #name: simclr_info_nce_loss
      #simclr_info_nce_loss:
      #  temperature: 0.5
      #  buffer_params:
      #    embedding_dim: 128
      name: pawpro_loss 
      pawpro_loss:
        world_size: 1
        num_protos: 64
        temperature: 1.0
        sharpening_temperature: 0.25
        label_smoothing: 0.1
        me_max: True
        init_protos_with_embs_centroids: True
        reinit_protos_phase_interval: 10
  OPTIMIZER:
      name: sgd
      use_larc: True
      larc_config:
        clip: False
        trust_coefficient: 0.001
        eps: 0.00000001
      weight_decay: 0.000001
      momentum: 0.9
      nesterov: False
      # num_epochs: 100
      # num_epochs: 200
      # num_epochs: 400
      # num_epochs: 500
      # num_epochs: 600
      # num_epochs: 800
      num_epochs: 1000
      # num_epochs: 1
      # num_epochs: 2
      # num_epochs: 5
      regularize_bn: False
      regularize_bias: False
      param_schedulers:
        lr:
          auto_lr_scaling:
            auto_scale: True
            base_value: 3.2
            base_lr_batch_size: 256
          name: composite
          schedulers:
            - name: linear
              start_value: 0.08
              end_value: 3.2
            - name: cosine
              start_value: 3.2
              end_value: 0.032
          update_interval: step
          interval_scaling: [rescaled, fixed]
          # lengths: [0.1, 0.9]                 # 100ep
          # lengths: [0.05, 0.95]             # 200ep
          # lengths: [0.025, 0.975]           # 400ep
          # lengths: [0.02, 0.98]             # 500ep
          # lengths: [0.0166667, 0.9833333]   # 600ep
          # lengths: [0.0125, 0.9875]         # 800ep
          lengths: [0.01, 0.99]             # 1000ep
          # lengths: [0.0128, 0.9872]         # 1ep IG-1B
          # lengths: [0.00641, 0.99359]       # 2ep IG-1B
          # lengths: [0.002563, 0.997437]     # 5ep IG-1B = 50 ep IG-100M
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 2
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "./outputs/latest"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 50
    OVERWRITE_EXISTING: True
